
api:
  url: api.testnet.iotex.one:80
#keyStore: ["io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg-6356908ace09268130dee2b7de643314bbeb3683","io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms-da7e12ef57c236a06117c5e0d04a228e7181cf36"]
log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: s.log
  stdLogRedirect: true

runInterval: 20
wallet: .

transfer:
  from: ["io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg","xx"]
  to: ["io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms",""]
  amountInRau: 0
  gaslimit: 1000000
  gasprice: 1000000000000
  alertThreshold: 15
xrc20:
  contract: io1hhu3gwt5uankzl3zlp2cz8w0sl9uj336rq0334
  from: ["io1vdtfpzkwpyngzvx7u2mauepnzja7kd5rryp0sg","xx"]
  to: ["io1mflp9m6hcgm2qcghchsdqj3z3eccrnekx9p0ms",""]
  amount: 10
  gaslimit: 1000000
  gasprice: 1000000000000
  alertThreshold: 15